version: '3.8'

networks:
  keycloak-network:
    driver: bridge

services:
  keycloak-db:
    image: postgres:14
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "5437:5432"
    volumes:
      - ./keycloak-db:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      keycloak-network: null
  
  keycloak:
    build: .
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: keycloak-db
      DB_DATABASE: keycloak
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8890:8080"
      - "8444:8443"
    command: start-dev
    volumes:
      - ./:/opt/keycloak
    restart: unless-stopped
    networks:
      keycloak-network: null